# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
  batch: false
  branches:
    include:
      - main
      - release-*

variables:
  branch: $[ coalesce(variables['system.PullRequest.TargetBranch'], variables['build.SourceBranchName']) ]
  GO_VERSION: 1.15.8
  PATH: $(Agent.BuildDirectory)/go/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

pool:
  vmImage: ubuntu-20.04

steps:
  - task: GoTool@0
    inputs:
      version: $(GO_VERSION)
      goBin: $(Agent.BuildDirectory)/go/bin
    displayName: Install Go

  - checkout: self
    path: 'fabric-config'
    clean: true
    fetchDepth: 1
    displayName: Checkout Fabric Code

  - script: ci/install-tools.sh
    displayName: Install Tools

  - script: ci/lint.sh
    displayName: Vet and lint

  - script: go test -race ./...
    displayName: Run tests
